#!/usr/bin/env bash
set -e

python3 -m pip install --upgrade pip
python3 -m pip install pandas
python3 -m pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html